[2024-05-14T11:42:56.482+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ademe_models.train_model_task manual__2024-05-14T11:42:52.635091+00:00 [queued]>
[2024-05-14T11:42:56.795+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ademe_models.train_model_task manual__2024-05-14T11:42:52.635091+00:00 [queued]>
[2024-05-14T11:42:56.795+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-05-14T11:42:56.818+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): train_model_task> on 2024-05-14 11:42:52.635091+00:00
[2024-05-14T11:42:56.832+0000] {standard_task_runner.py:60} INFO - Started process 40389 to run task
[2024-05-14T11:42:56.840+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ademe_models', 'train_model_task', 'manual__2024-05-14T11:42:52.635091+00:00', '--job-id', '209', '--raw', '--subdir', 'DAGS_FOLDER/predict.py', '--cfg-path', '/tmp/tmp_jf_3de_']
[2024-05-14T11:42:56.843+0000] {standard_task_runner.py:88} INFO - Job 209: Subtask train_model_task
[2024-05-14T11:42:56.922+0000] {task_command.py:423} INFO - Running <TaskInstance: ademe_models.train_model_task manual__2024-05-14T11:42:52.635091+00:00 [running]> on host 86724742ac03
[2024-05-14T11:42:57.055+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ademe_models' AIRFLOW_CTX_TASK_ID='train_model_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-14T11:42:52.635091+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-14T11:42:52.635091+00:00'
[2024-05-14T11:42:57.226+0000] {logging_mixin.py:188} INFO -    etiquette_dpe  ...  type_energie_n_1
0              0  ...                 4
1              0  ...                 4
2              0  ...                 4
3              0  ...                 4
4              0  ...                 4

[5 rows x 5 columns]
[2024-05-14T11:42:57.324+0000] {logging_mixin.py:188} WARNING - 2024/05/14 11:42:57 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2024-05-14T11:42:57.369+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/predict.py", line 197, in train_model
    train = TrainDPE(data)
  File "/opt/airflow/dags/predict.py", line 60, in __init__
    data = data[data[target] >= 0].copy()
TypeError: 'NoneType' object is not subscriptable
[2024-05-14T11:42:57.384+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=ademe_models, task_id=train_model_task, execution_date=20240514T114252, start_date=20240514T114256, end_date=20240514T114257
[2024-05-14T11:42:57.409+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 209 for task train_model_task ('NoneType' object is not subscriptable; 40389)
[2024-05-14T11:42:57.455+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-14T11:42:57.498+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
