[2024-05-15T11:31:56.449+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_ademe_data.interrogate_api manual__2024-05-15T11:31:53.032848+00:00 [queued]>
[2024-05-15T11:31:56.460+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_ademe_data.interrogate_api manual__2024-05-15T11:31:53.032848+00:00 [queued]>
[2024-05-15T11:31:56.461+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-05-15T11:31:56.479+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): interrogate_api> on 2024-05-15 11:31:53.032848+00:00
[2024-05-15T11:31:56.490+0000] {standard_task_runner.py:60} INFO - Started process 2157 to run task
[2024-05-15T11:31:56.498+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'get_ademe_data', 'interrogate_api', 'manual__2024-05-15T11:31:53.032848+00:00', '--job-id', '288', '--raw', '--subdir', 'DAGS_FOLDER/load.py', '--cfg-path', '/tmp/tmp6grydtgx']
[2024-05-15T11:31:56.502+0000] {standard_task_runner.py:88} INFO - Job 288: Subtask interrogate_api
[2024-05-15T11:31:56.580+0000] {task_command.py:423} INFO - Running <TaskInstance: get_ademe_data.interrogate_api manual__2024-05-15T11:31:53.032848+00:00 [running]> on host 583e99962ff2
[2024-05-15T11:31:56.691+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='get_ademe_data' AIRFLOW_CTX_TASK_ID='interrogate_api' AIRFLOW_CTX_EXECUTION_DATE='2024-05-15T11:31:53.032848+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-15T11:31:53.032848+00:00'
[2024-05-15T11:31:56.694+0000] {load.py:117} ERROR - An unexpected error occurred: name 'isfile' is not defined
[2024-05-15T11:31:56.694+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-05-15T11:31:56.706+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=get_ademe_data, task_id=interrogate_api, execution_date=20240515T113153, start_date=20240515T113156, end_date=20240515T113156
[2024-05-15T11:31:56.752+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-05-15T11:31:56.785+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
